version: '2'
services:
  auth-proxy:
    build: .
    ports:
     - "8080:8080"
    # This placeholders should be overwritten with the .env file or environmenr variables
    environment:     
      TARGET_URL:
      REALM:
      REALM_PUBLIC_KEY:
      AUTH_SERVER_URL:
      RESOURCE:
      SECRET:
  # Demo Application      
  demoapp:
    image: vad1mo/hello-world-service
    ports:
      - "5050:5050"